// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yoiztmusyxefgbgrgmgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvaXp0bXVzeXhlZmdiZ3JnbWdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNjc3NDIsImV4cCI6MjA2Mzc0Mzc0Mn0.9097gnYvMesfcQovaXgrnHuAt_NlBwl3v5NDKJXIUT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);